name: Invoke API

on:
  workflow_run:
    workflows: ["Register"]
    types:
      - completed
  workflow_dispatch:

jobs:
  invoke:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Python And Poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v8

      - name: Install Requirement
        run: poetry install

      - name: Test API
        env:
          PASSWD: ${{ secrets.PASSWD }}
        run: bash routine.sh

      - name: Commit And Push
        run: bash reset.sh "Update App Config"
